export const ADD_TODO = 'ADD_TODO';
export const DELETE_TODO = 'DELETE_TODO';
export const EDIT_TODO = 'EDIT_TODO';
export const COMPLETE_TODO = 'COMPLETE_TODO';
export const COMPLETE_ALL = 'COMPLETE_ALL';
export const CLEAR_COMPLETED = 'CLEAR_COMPLETED';

export const ADD_MAIN_FOCUS = 'ADD_MAIN_FOCUS';
export const COMPLETE_MAIN_FOCUS = 'COMPLETE_MAIN_FOCUS';
export const DELETE_MAIN_FOCUS = 'DELETE_MAIN_FOCUS';
